name: Tango Ghost
favicon: null
layout_spectrum: 0.9859937797300518
typography_spectrum: 0.5349779375828803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8370614191517234
  lightness: 0.1837757807224989
  saturation: 0.4518810282461345
  rhythmicContrast: 0.3347973849158734
purpose: []
